-- CREATE OR REPLACE FUNCTION acs_object_type__create_type(
--    p_object_type varchar,
--    p_pretty_name varchar,
--    p_pretty_plural varchar,
--    p_supertype varchar,
--    p_table_name varchar,           -- default null
--    p_id_column varchar,            -- default null
--    p_package_name varchar,         -- default null
--    p_abstract_p boolean,           -- default 'f'
--    p_type_extension_table varchar, -- default null
--    p_name_method varchar,          -- default null
--    p_create_table_p boolean,       -- default 'f'
--    p_dynamic_p boolean             -- default 'f'
--
-- ) RETURNS integer AS $$
-- DECLARE
--   v_package_name                      acs_object_types.package_name%TYPE;
--   v_supertype                         acs_object_types.supertype%TYPE;
--   v_name_method                       varchar;
--   v_idx                               integer;
--   v_temp_p                            boolean;
--   v_supertype_table                   acs_object_types.table_name%TYPE;
--   v_id_column                         acs_object_types.id_column%TYPE;
--   v_table_name                        acs_object_types.table_name%TYPE;
-- BEGIN
-- TOOK STUFF FROM HERE
--
--
--
--     return 0;
-- END;
-- $$ LANGUAGE plpgsql;
